# Generated by Django 5.1 on 2024-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='cis',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
