# Generated by Django 5.0.7 on 2024-08-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='structure_images/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.structure')),
            ],
        ),
    ]
