# Generated by Django 5.1 on 2024-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_structure_cis'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='calendar_id_booking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
