# Generated by Django 5.0.7 on 2024-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_structureimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='paid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='UNPAID', max_length=20),
        ),
    ]
