# Generated by Django 5.1 on 2024-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_reservation_paid_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structureimage',
            old_name='description',
            new_name='alt',
        ),
    ]
