# Generated by Django 5.1 on 2024-10-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_room_calendar_id_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmspugliaxml',
            name='date',
            field=models.DateField(default='2024-10-10'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dmspugliaxml',
            unique_together={('structure', 'date')},
        ),
    ]
