# Generated by Django 5.1 on 2024-10-10 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dmspugliaxml_date_alter_dmspugliaxml_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmspugliaxml',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
