# Generated by Django 5.1 on 2024-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
