# Generated by Django 5.1 on 2024-10-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dmspugliaxml_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dmspugliaxml',
            unique_together=set(),
        ),
    ]
