# Generated by Django 5.1 on 2024-08-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_reservation_number_of_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInfoAllogiatiWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAllogiatiWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allogiati_web_user', models.CharField(max_length=100)),
                ('alloggiati_web_password', models.CharField(max_length=100)),
                ('wskey', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_allogiati_web', to='accounts.structure')),
            ],
        ),
    ]
