# Generated by Django 5.1 on 2024-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tokeninfoallogiatiweb_userallogiatiweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeninfoallogiatiweb',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
