# Generated by Django 5.1 on 2024-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tokeninfoallogiatiweb_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinCategoryChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tipo_alloggiato', 'Tipo Alloggiato'), ('comune_di_nascita', 'Comune di Nascita'), ('stato_di_nascita', 'Stato di Nascita'), ('cittadinanza', 'Cittadinanza'), ('tipo_documento', 'Tipo Documento'), ('luogo_rilascio_documento', 'Luogo Rilascio Documento')], max_length=50)),
                ('codice', models.CharField(blank=True, max_length=10, null=True)),
                ('descrizione', models.CharField(max_length=100)),
            ],
        ),
    ]
