services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - database
    env_file:
      - ./.env

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A config worker -l info -E
    volumes:
      - .:/code
    env_file:
      - ./.env
    user: "celeryuser"
    depends_on:
      - redis
      - app
      - database

  database:
    image: postgres:16.0
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
