services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - redis

  redis:
    image: redis:7

  celery:
    build: .
    restart: always
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - app

  caddy:
    build: ./caddy
    restart: always
    ports:
      - ${CADDY_PORT}:80
      - "443:443"
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${CADDY_EMAIL}

volumes:
  static_volume:
  media_volume: