# STATUS_CHOICES VALUES
COMPLETE = 'COMPLETE'
PENDING_COMPLETE_DATA = 'PENDING_EXTRA_DATA'

# TYPE VALUES
CUSTOMER = 'CUSTOMER'
ADMIN = 'ADMIN'


STATUS_CHOICES = (
    (COMPLETE, 'Complete'),
    (PENDING_COMPLETE_DATA, 'Pending Complete Data'),
)


TYPE_VALUES = (
    (CUSTOMER, 'Customer'),
    (ADMIN, 'Admin'),
)
